# Generated by Django 3.0.6 on 2020-10-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome completo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('empresas', models.ManyToManyField(related_name='funcionarios_list', to='empresa.Empresa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
