# Generated by Django 3.0.6 on 2020-10-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
